# Generated by Django 5.1.1 on 2024-09-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='parent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
