# Generated by Django 5.1.1 on 2024-09-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0002_ledger_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='name',
            field=models.TextField(max_length=255),
        ),
    ]
